parameters:
    php_orchestra_display.display_block_manager.class: PHPOrchestra\DisplayBundle\DisplayBlock\DisplayBlockManager

    php_orchestra_display.display.carrousel.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\CarrouselStrategy
    php_orchestra_display.display.contact.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\ContactStrategy
    php_orchestra_display.display.footer.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\FooterStrategy
    php_orchestra_display.display.header.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\HeaderStrategy
    php_orchestra_display.display.menu.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\MenuStrategy
    php_orchestra_display.display.news.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\NewsStrategy
    php_orchestra_display.display.sample.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\SampleStrategy
    php_orchestra_display.display.tiny_mce_wysiwyg.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\TinyMCEWysiwygStrategy

services:
    php_orchestra_display.display_block_manager:
        class: %php_orchestra_display.display_block_manager.class%
        arguments: [@templating]

    php_orchestra_display.display.carrousel:
        class: %php_orchestra_display.display.carrousel.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.contact:
        class: %php_orchestra_display.display.contact.class%
        arguments: [@form.factory]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.footer:
        class: %php_orchestra_display.display.footer.class%
        arguments: [@php_orchestra_model.repository.node, @router]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.header:
        class: %php_orchestra_display.display.header.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.menu:
        class: %php_orchestra_display.display.menu.class%
        arguments: [@php_orchestra_model.repository.node, @router]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.news:
        class: %php_orchestra_display.display.news.class%
        arguments: [@php_orchestra_model.repository.content]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.sample:
        class: %php_orchestra_display.display.sample.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.tiny_mce_wysiwyg:
        class: %php_orchestra_display.display.tiny_mce_wysiwyg.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
