parameters:
    php_orchestra_display.display_block_manager.class: PHPOrchestra\DisplayBundle\DisplayBlock\DisplayBlockManager

    php_orchestra_display.display.carrousel.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\CarrouselStrategy
    php_orchestra_display.display.contact.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\ContactStrategy
    php_orchestra_display.display.footer.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\FooterStrategy
    php_orchestra_display.display.header.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\HeaderStrategy
    php_orchestra_display.display.menu.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\MenuStrategy
    php_orchestra_display.display.news.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\NewsStrategy
    php_orchestra_display.display.sample.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\SampleStrategy
    php_orchestra_display.display.tiny_mce_wysiwyg.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\TinyMCEWysiwygStrategy
    php_orchestra_display.display.configurable_content.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\ConfigurableContentStrategy
    php_orchestra_display.display.sub_menu.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\SubMenuStrategy
    php_orchestra_display.display.content_list.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\ContentListStrategy
    php_orchestra_display.display.content.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\ContentStrategy
    php_orchestra_display.display.language_list.class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\LanguageListStrategy

services:
    php_orchestra_display.display_block_manager:
        class: %php_orchestra_display.display_block_manager.class%
        arguments: [@templating]

    php_orchestra_display.display.carrousel:
        class: %php_orchestra_display.display.carrousel.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.contact:
        class: %php_orchestra_display.display.contact.class%
        arguments: [@form.factory, @router]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.footer:
        class: %php_orchestra_display.display.footer.class%
        arguments: [@php_orchestra_model.repository.node, @router, @request_stack]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.header:
        class: %php_orchestra_display.display.header.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.menu:
        class: %php_orchestra_display.display.menu.class%
        arguments: [@php_orchestra_model.repository.node, @router, @request_stack]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.news:
        class: %php_orchestra_display.display.news.class%
        arguments: [@php_orchestra_model.repository.content]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.sample:
        class: %php_orchestra_display.display.sample.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.tiny_mce_wysiwyg:
        class: %php_orchestra_display.display.tiny_mce_wysiwyg.class%
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.configurable_content:
        class: %php_orchestra_display.display.configurable_content.class%
        arguments: [@php_orchestra_model.repository.content]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.sub_menu:
        class: %php_orchestra_display.display.sub_menu.class%
        arguments: [@php_orchestra_model.repository.node, @router, @request_stack]
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.content_list:
        class: %php_orchestra_display.display.content_list.class%
        arguments:
            - @php_orchestra_model.repository.content
            - @router
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.content:
        class: %php_orchestra_display.display.content.class%
        arguments:
            - @php_orchestra_model.repository.content
            - @request_stack
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.language_list:
        class: %php_orchestra_display.display.language_list.class%
        arguments:
            - @form.factory
            - @php_orchestra.manager.current_site
            - @php_orchestra_model.repository.site
            - @request_stack
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.youtube:
        class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\YoutubeStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.dailymotion:
        class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\DailymotionStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.vimeo:
        class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\VimeoStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.gmap:
        class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\GmapStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
    php_orchestra_display.display.add_this:
        class: PHPOrchestra\DisplayBundle\DisplayBlock\Strategies\AddThisStrategy
        tags:
            - { name: php_orchestra_display.display_block.strategy }
