parameters:
    php_orchestra_cms.manager.tree.class: PHPOrchestra\DisplayBundle\Manager\TreeManager

services:
    php_orchestra_cms.manager.tree:
        class: %php_orchestra_cms.manager.tree.class%