parameters:
    php_orchestra_display.manager.tree.class: PHPOrchestra\DisplayBundle\Manager\TreeManager

services:
    php_orchestra_display.manager.tree:
        class: %php_orchestra_display.manager.tree.class%