parameters:
    open_orchestra_display.manager.tree.class: OpenOrchestra\DisplayBundle\Manager\TreeManager
    open_orchestra_display.manager.site.class: OpenOrchestra\DisplayBundle\Manager\SiteManager

services:
    open_orchestra_display.manager.tree:
        class: %open_orchestra_display.manager.tree.class%
    open_orchestra_display.manager.site:
        class: %open_orchestra_display.manager.site.class%
        arguments:
            - @request_stack
