parameters:
#--[EXTEND SYMFONY 2 ROUTING]---#

    router.class : 'PHPOrchestra\DisplayBundle\Routing\PhpOrchestraRouter'
    router.options.generator_class : 'PHPOrchestra\DisplayBundle\Routing\PhpOrchestraUrlGenerator'
    router.options.generator_base_class : 'PHPOrchestra\DisplayBundle\Routing\PhpOrchestraUrlGenerator'

services:
