parameters:
    open_orchestra_display.bbcode.code_definitions.class: OpenOrchestra\DisplayBundle\BBcode\DisplayBundleBBcodeCollection

services:
    open_orchestra_display.bbcode.code_definitions:
        class: %open_orchestra_display.bbcode.code_definitions.class%
        arguments:
            - @open_orchestra_bbcode.definition.factory
        tags:
            - { name: open_orchestra_bbcode.code_definitions }
