parameters:
    open_orchestra_display.bbcode_collection.class: OpenOrchestra\DisplayBundle\BBcode\DisplayBundleBBcodeCollection

services:
    open_orchestra_display.bbcode_collection:
        class: %open_orchestra_display.bbcode_collection.class%
        arguments:
            - @open_orchestra_bbcode.definition.factory
        tags:
            - { name: open_orchestra_bbcode.code_definitions }
