parameters:
    php_orchestra_cms.twig.tree.extension.class: PHPOrchestra\DisplayBundle\Twig\TreeHelperExtension

services:
    php_orchestra_cms.twig.tree.extension:
        class: %php_orchestra_cms.twig.tree.extension.class%
        arguments: [@php_orchestra_display.manager.tree]
        tags:
            - { name: twig.extension }
