language: php

php:
  - 5.4

sudo: false

cache:
  directories:
    - ~/.composer/cache

before_install: 
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist --no-progress

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=9e8441a5e2145a633a1fe2e3159cda6de12bd5b24e262e58a34875715503aba7 ./bin/test-reporter
