parameters:
    open_orchestra_bbcode.validators :
        url : JBBCode\validators\UrlValidator
        css_color : JBBCode\validators\CssColorValidator

    open_orchestra_bbcode.code_definitions :
        title :
            tag : h
            html : <h{option}>{param}</h{option}>
            parameters :
                use_option : true

        bold :
            tag : b
            html : <strong>{param}</strong>
        italic :
            tag : i
            html : <em>{param}</em>
        underline :
            tag : u
            html : <u>{param}</u>
        line-through :
            tag : s
            html : <strike>{param}</strike>
        center :
            tag : center
            html : <center>{param}</center>

        quote :
            tag : quote
            html : <blockquote>{param}</blockquote>
        code :
            tag : code
            html : <code>{param}</code>

        table :
            tag : table
            html : <table>{param}</table>
        table_row :
            tag : tr
            html : <tr>{param}</tr>
        heading_cell :
            tag : th
            html : <th>{param}</th>
        content_cell :
            tag : td
            html : <td>{param}</td>

        color :
            tag : color
            html : <span style="color: {option}">{param}</span>
            parameters :
                use_option : true
                option_validator : css_color

        unordered_list :
            tag : ul
            html : <ul>{param}</ul>

        ordered_list :
            tag : ol
            html : <ol>{param}</ol>

        list_item :
            tag : li
            html : <li>{param}</li>

        link :
            tag : url
            html : <a href="{param}">{param}</a>
            parameters :
                parse_content : false
                body_validator : url
        link_named :
            tag : url
            html : <a href="{option}">{param}</a>
            parameters :
                use_option : true
                parse_content : true
                option_validator : url

        img :
            tag : img
            html : <img src="{param}" />
            parameters :
                use_option : false
                parse_content : false
                body_validator : url
        img_with_alt :
            tag : img
            html : <img src="{param}" alt="{option}" />
            parameters :
                use_option : true
                parse_content : false
                body_validator : url
