parameters:
    open_orchestra_bbcode.jbbcode_definition.class : JBBCode\CodeDefinition

    open_orchestra_bbcode.parser.class : OpenOrchestra\BBcodeBundle\Parser\BBcodeParser
    open_orchestra_bbcode.definition.factory.class : OpenOrchestra\BBcodeBundle\Definition\BBcodeDefinitionFactory

services:
    open_orchestra_bbcode.jbbcode_parser:
        class: %open_orchestra_bbcode.jbbcode_parser.class%

    open_orchestra_bbcode.parser:
        class: %open_orchestra_bbcode.parser.class%

    open_orchestra_bbcode.definition.factory:
        class: %open_orchestra_bbcode.definition.factory.class%
        arguments:
            - %open_orchestra_bbcode.jbbcode_definition.class%
