parameters:
    open_orchestra_bbcode.bbcode_definition.class : OpenOrchestra\BBcodeBundle\Definition\BBcodeDefinition

    open_orchestra_bbcode.parser.class : OpenOrchestra\BBcodeBundle\Parser\BBcodeParser
    open_orchestra_bbcode.definition.factory.class : OpenOrchestra\BBcodeBundle\Definition\BBcodeDefinitionFactory

services:
    open_orchestra_bbcode.parser:
        class: %open_orchestra_bbcode.parser.class%

    open_orchestra_bbcode.definition.factory:
        class: %open_orchestra_bbcode.definition.factory.class%
        arguments:
            - %open_orchestra_bbcode.bbcode_definition.class%
