parameters:
    open_orchestra_bbcode.jbbcode_parser.class : JBBCode\Parser
    open_orchestra_bbcode.bbcode_parser.class : OpenOrchestra\BBcodeBundle\BBcodeParser

services:
    open_orchestra_bbcode.jbbcode_parser:
        class: %open_orchestra_bbcode.jbbcode_parser.class%

    open_orchestra_bbcode.bbcode_parser:
        class: %open_orchestra_bbcode.bbcode_parser.class%
        arguments :
            - [open_orchestra_bbcode.jbbcode_parser]
            - [open_orchestra_bbcode.configured_code_definition_set]
